# Generated by Django 6.0.3 on 2026-05-03 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_note_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'note')},
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('user', 'note')},
        ),
    ]
